### ISSUE TITLE
Runtime errors on brand new server startup

### ISSUE THREAD

**Issue by tmad40blue** [tgstation/-tg-station#15032]
Hi, I've just gotten my server running for the very first time - nobody has ever joined the server before - and I'm receiving quite a few runtime errors upon startup.

If it helps out, I'm running my server on CentOS 7.

Please let me know if there's any additional info I can provide to assist with this. Thanks!

````
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (149,29,1) (/turf/simulated/floor/bluegrid)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (149,29,1) (/turf/simulated/floor/bluegrid))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (151,33,1) (/turf/simulated/floor/bluegrid)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (151,33,1) (/turf/simulated/floor/bluegrid))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (148,45,1) (/turf/simulated/floor/bluegrid)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (148,45,1) (/turf/simulated/floor/bluegrid))
runtime error: Cleanbot is being instantiated
proc name: stack trace (/proc/stack_trace)
  source file: cleanbot.dm,31
  usr: the Cleanbot (/mob/living/simple_animal/bot/cleanbot)
  src: null
  usr.loc: the floor (153,50,1) (/turf/simulated/floor/plasteel)
  call stack:
stack trace("Cleanbot is being instantiated")
the Cleanbot (/mob/living/simple_animal/bot/cleanbot): New(the floor (153,50,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeEmpProof (/obj/machinery/camera/proc/upgradeEmpProof)
  source file: presets.dm,75
  usr: null
  src: the security camera (/obj/machinery/camera/emp_proof)
  src.loc: the plating (105,55,1) (/turf/simulated/floor/plating/airless)
  call stack:
the security camera (/obj/machinery/camera/emp_proof): upgradeEmpProof()
the security camera (/obj/machinery/camera/emp_proof): New(the plating (105,55,1) (/turf/simulated/floor/plating/airless))
runtime error: Cannot read null.upgrades
proc name: upgradeEmpProof (/obj/machinery/camera/proc/upgradeEmpProof)
  source file: presets.dm,75
  usr: null
  src: the security camera (/obj/machinery/camera/emp_proof)
  src.loc: the plating (121,55,1) (/turf/simulated/floor/plating/airless)
  call stack:
the security camera (/obj/machinery/camera/emp_proof): upgradeEmpProof()
the security camera (/obj/machinery/camera/emp_proof): New(the plating (121,55,1) (/turf/simulated/floor/plating/airless))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (151,55,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (151,55,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeEmpProof (/obj/machinery/camera/proc/upgradeEmpProof)
  source file: presets.dm,75
  usr: null
  src: the security camera (/obj/machinery/camera/emp_proof)
  src.loc: the plating (105,67,1) (/turf/simulated/floor/plating/airless)
  call stack:
the security camera (/obj/machinery/camera/emp_proof): upgradeEmpProof()
the security camera (/obj/machinery/camera/emp_proof): New(the plating (105,67,1) (/turf/simulated/floor/plating/airless))
runtime error: Cannot read null.upgrades
proc name: upgradeEmpProof (/obj/machinery/camera/proc/upgradeEmpProof)
  source file: presets.dm,75
  usr: null
  src: the security camera (/obj/machinery/camera/emp_proof)
  src.loc: the plating (121,67,1) (/turf/simulated/floor/plating/airless)
  call stack:
the security camera (/obj/machinery/camera/emp_proof): upgradeEmpProof()
the security camera (/obj/machinery/camera/emp_proof): New(the plating (121,67,1) (/turf/simulated/floor/plating/airless))
runtime error: Cleanbot is being instantiated
proc name: stack trace (/proc/stack_trace)
  source file: cleanbot.dm,31
  usr: C.L.E.A.N. (/mob/living/simple_animal/bot/cleanbot)
  src: null
  usr.loc: the floor (133,126,1) (/turf/simulated/floor/plasteel)
  call stack:
stack trace("Cleanbot is being instantiated")
C.L.E.A.N. (/mob/living/simple_animal/bot/cleanbot): New(the floor (133,126,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (109,130,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (109,130,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (117,130,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (117,130,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (83,146,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (83,146,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (99,152,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (99,152,1) (/turf/simulated/floor/plasteel))
runtime error: Cannot read null.upgrades
proc name: upgradeMotion (/obj/machinery/camera/proc/upgradeMotion)
  source file: presets.dm,84
  usr: null
  src: the motion-sensitive security ... (/obj/machinery/camera/motion)
  src.loc: the floor (112,182,1) (/turf/simulated/floor/plasteel)
  call stack:
the motion-sensitive security ... (/obj/machinery/camera/motion): upgradeMotion()
the motion-sensitive security ... (/obj/machinery/camera/motion): New(the floor (112,182,1) (/turf/simulated/floor/plasteel))
````

**Comment by KorPhaeron** [comment]
@Razharas

**Comment by phil235** [comment]
This was likely fixed by #15001

**Comment by xxalpha** [comment]
If it's the cameras, yes, probably.

There's also the cleanbot runtime in that paste, which is intended to happen.

**Comment by tmad40blue** [comment]
Any updates on this issue? Still receiving the same errors when starting up my server.

**Comment by xxalpha** [comment]
Cleanbot runtime is intended.

**Comment by phil235** [comment]
@tmad40blue The camera runtimes shouldn't appear anymore if you're using the current tg code.

**Comment by duncathan** [comment]
@tmad40blue the cleanbot runtimes are intended to help us solve a mystery bug. Are they the only ones occurring?
