### ISSUE TITLE
Text bar is in bold now?

### ISSUE THREAD

**Issue by Shapsy** [tgstation/-tg-station#15044]
Also the text cuts off at the bottom for me so I can't tell the difference between v's and y's, i's and j's, and probably some other letters too
![](http://puu.sh/mOsVa/ebedfb7826.png)

**Comment by neersighted** [comment]
Well, I tested across two machines, did not have this issue. I'll see what I can do.

**Comment by xxalpha** [comment]
Is this byond's chat bar? It's not bold for me.

**Comment by neersighted** [comment]
Yeah its the built in input bar, and it was not bold for me either working on this. @Shapsy clear your skin cache please.

**Comment by Shapsy** [comment]
Where's that option? Clearing the normal cache through byond didn't help

**Comment by neersighted** [comment]
Delete the cache in your BYOND folder.
Anyway, fixed.

![FIXED](https://camo.githubusercontent.com/5eea6195062cd85ac712a95bcecd2b0025f2ec4a/687474703a2f2f692e696d6775722e636f6d2f624e55356c786e2e706e67)

**Comment by Shapsy** [comment]
no dice @neersighted, I exited byond, deleted the skins folder and joined the game, and the text was still getting cut off
