### ISSUE TITLE
Tesla can kill you in maint on meta/through walls

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/-tg-station#15655]
http://i.imgur.com/mcsYpix.png

I died where the X is, and here you can see the beam going through a wall.

Doesn't seem quite right

**Comment by Zilenan91** [comment]
Already reported on the forum thread for metastation, but keep this up anyways so people see it.

**Comment by PKPenguin321** [comment]
this is metastation, by the way

**Comment by Zilenan91** [comment]
It says in the title that it's meta

**Comment by PKPenguin321** [comment]
oh yeah true
it's sneaky though

**Comment by Metacide** [comment]
Will fix this soon.

**Comment by PKPenguin321** [comment]
i thought this was fixed at some point

**Comment by phil235** [comment]
I don't see any map change in the engine area layout, so it's probably still happening.

**Comment by Metacide** [comment]
I was under the impression it was fixed when posters stopped conducting, but I'll do a check tonight to see if I still need to put in extra grounding rods.

**Comment by Iamgoofball** [comment]
check that the signs also block conduction

**Comment by Metacide** [comment]
No, the problem was still there it seems. Destroyed one of the cameras too.

So I've added more grounding rods - might be overkill but seems to work:

![New Grounding Rods](https://dl.dropboxusercontent.com/u/858120/NewGroundingRods.png)
