### ISSUE TITLE
Can't see through windows in robo, R&D

### ISSUE THREAD

**Issue by TheVekter** [tgstation/-tg-station#3127]
![robowindow](https://f.cloud.github.com/assets/7019927/2480946/41686f00-b0ce-11e3-9122-45f509a63097.png)

Exactly what it says on the tin. Even when the shutters are up, you can't see through these windows. This includes the windows at the bottom wall of Robo, and both the top and bottom sets of windows in R&D. The windows overlooking the recharge bay and the mining machine work fine, strangely enough.

**Comment by Dorsisdwarf** [comment]
Someone please say this was fixed

**Comment by Aranclanos** [comment]
tinted windows (only the ones who are side) are still completly bugged and they are still present in the game. 
And not only available for add them in the map, you can already see them in the station, for example, robotics, like in the screenshot that I posted 5 months ago
