### ISSUE TITLE
Autolathe accepts cyborg tools

### ISSUE THREAD

**Issue by Actionb** [tgstation/-tg-station#6167]
Just now, I accidentally inserted my engiborg's flashlight into an autolathe. I haven't tested if it accepts other modules like the RCD etc as well. Recharging in a borg station did not give me a flashlight back.

**Comment by Dorsisdwarf** [comment]
I think was fixed. Can anyone confirm?

**Comment by phil235** [comment]
Nope, still happens. Easy to fix though, this bug doesn't happen with destructive analyzer, so just use whatever check it's using.

**Comment by WJohn** [comment]
Just happened today, was not fixed yet.
