### ISSUE TITLE
Browser windows display "\improper Item" as "ÿItem"

### ISSUE THREAD

**Issue by kingofkosmos** [tgstation/-tg-station#8297]
If you insert a Donk-pocket into a microwave, it says

Ingredients: ÿDonk-pocket: 1
Same with a warm Donk-pocket:
ÿWarm Donk-pocket: 1

Revision: d525fd6a875eebe42b55bd8b2b129ffa56567065

**Comment by Menshin** [comment]
Unfixable, it's Byond control character for \improper that isn't stripped (lots of duplicate for this one iirc).

**Comment by Jalleo** [comment]
Is there a issue report for that on byond?

**Comment by Menshin** [comment]
http://www.byond.com/forum/?post=1477921

(MrPerson mentioned this specific issue at the end of the thread)

**Comment by kingofkosmos** [comment]
Still reproduceable.
![image](https://cloud.githubusercontent.com/assets/5420151/9979828/1ab36b10-5f89-11e5-9ef2-9804daf66f28.png)

**Comment by phil235** [comment]
Warm Donk-Pocket doesn't have \improper because the name's first letter isn't capitalized ("warm Donk-pocket"). This bug is still unchanged.

**Comment by Dorsisdwarf** [comment]
If we can't resolve an issue, we can't fix the issue.

If we can't fix something, it shouldn't be on the tracker

**Comment by MrPerson** [comment]
@Dorsisdwarf This is totally fixable. Read the thread that was linked earlier, it actually explains exactly how to fix this.

**Comment by tkdrg** [comment]
fixed in 509

**Comment by Jalleo** [comment]
@tkdrg not fixed http://imgur.com/62wHVqr on latest 509 and on sybil just now with goofballs test merge running to do with tesla engine

**Comment by tkdrg** [comment]
ok

**Comment by MrStonedOne** [comment]
@neersighted you could partially fix this by stripping out that character in nanoui

**Comment by neersighted** [comment]
Yeah NanoUI handles this
