### ISSUE TITLE
Double space after people's names before dialogue verb

### ISSUE THREAD

**Issue by Amnestik** [tgstation/-tg-station#9420]
Blah Blahson (as Unknown)__says, "Blah blah blah"
Blah Blahson__buzzes, "Blah blah, blah."
Blahson__buzzes, "Blah blah blah."

Added underscores so you could see what I mean. Github automatically removes extra spaces.

**Comment by Miauw62** [comment]
fairly sure this is a dupe.
maybe i should fix this sometime

**Comment by Miauw62** [comment]
as far as i can tell, this does not happen except for AIs, in which case this is a dupe.

**Comment by Amnestik** [comment]
It was happening for everyone, but I guess it was partially fixed since then.
