### ISSUE TITLE
Atmospherics has a strong tendency to deadlock.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/-tg-station#9787]
I've ran several experiments this week to observe scrubbers and vents cleaning a room and these are my observations:

The amount of gas exchanged between turfs depend of the pressure differencial between the turfs. While it is perfectly realistic, there is an issue:

A scrubber is working on a room full of toxin, it does so by removing toxin from the turf it's sitting on. the pressure difference (or something?) activate the neighbor turfs and the room get mixed.

The problem that ocured every single time in my tests is that at a low enough (but still letal) concentration of toxins once the scrubber removed toxin on it's turf, the pressure difference between it and the neighbouring turfs is minuscule, and as a result, the stirring doesn't occur and the system effectively "halt".

One solution could be to add to the pressure based gas exchange a diffusion factor that is based on the absolute difference in gas mixture that would "simulates" some kind of passive mixing ( in the real world the heavier gas ends up spreading to an entire room's lowest layer through gravity as unstirred gasses start to separate by density)

At low concentration plasma in this example would spread to the entire room, diffusing itself below the lethal concentration (and visually disappearing)
![Low concentration test](https://i.imgur.com/5C3jpcP.png)

You can see the deadlock occuring here, the active set of scrubbers are free from plasma and at some point the system "halt" in this state and will remain as such even after an hour.
![High concentration test](https://i.imgur.com/QKQ7BJp.png)

**Comment by duncathan** [comment]
In addition to the above possible solution that was discussed, there were a couple others. 
First was a draft system in which scrubbers were replaced with constantly siphoning vents, so that there was a constant airflow. It turned out to actually be slower than scrubbers as they are, so it's out. 
Second was the idea of having them scrub 3x3 areas round them. I left before (if) it was tested, but I think that it's more of a bandaid fix, not addressing the real problem. 
Third was the idea of having them scrub the entire room. I have no idea how possible or good this idea is but it seems like it'd address the issue with scrubbers being useless.

**Comment by RemieRichards** [comment]
Not entirely sure if it's related but a week ago as AI I spent what felt like the entire round emptying toxins of well, toxins after a leak.

I had to constantly toggle the scrubber modes to get the last few turfs and % of plasma to go away.

**Comment by kyrahabattoir** [comment]
@RemieRichards Sounds like reactivating the scrubber would wake up the room only for it to deadlock again?

And yeah the draft system proved to be a failure, somehow it maintained a boatload of tiles active but did not manage to filter more. I had a recirculation setup that would filter the toxin out but the extra volume (vents do not filter) while not clogging the pipe, made the process less efficient in the end.

I also noticed a certain "bias" for north facing tiles but that could have been a coincidence.

I tried to increase the scrubber pickup area to 3x3 but failed, I can read dmscript just fine, but writing it is another story.

**Comment by Supermichael777** [comment]
the only way to truly get rid of harmful gasses at the moment is literally to symphony out the room and replace the air. this predictably takes forever and makes the room useless for the cycling period

**Comment by kyrahabattoir** [comment]
I wanted to add that comparatively, the overpressure due to the introduction of the new gas clears up very quickly. So the problem is definitely that gas mixing is completely pressure bound rather than pressure+content bound.

**Comment by Jalleo** [comment]
How about making certain types of gas like plasma clump together and refuse to spread to a lower percentage content and if reduced to lower from that percentage it moves back to where there is a higher plasma content?

**Comment by MrStonedOne** [comment]
The issue here is that the minimum plasma difference to spread define is apparently higher than the minimum plasma to exist.

These should be equalized out, so that when the plasma amount gets too low to spread with a tile that has zero, it stops existing.

From what i've seen with the code, there isn't some magic pressure difference the tile has to have to spread, its done on each gas independently, but I might have missed something.

**Comment by kyrahabattoir** [comment]
Plasma presence is fine tho it would eventually diffuse to a room until it spread to it entirely. if that makes it drop under the dangerosity level it would stop showing the purple particles.

@Jalleo the issue IS that it won't mix once pressure equalised. Realistically it should keep mixing until turf to turf composition roughly equalised.

**Comment by Jalleo** [comment]
True but i think we shouldnt push for that sort of realidm since it would make gameplay worse for dealing with leaks.

**Comment by kyrahabattoir** [comment]
How would it make it worse? Right now gasses behave like jello that refuses to move to get scrubbed away.

**Comment by WJohn** [comment]
This is actually a problem with fires, too. I tested out a big fire in the thunderdome, everything remains visually as plasma yet I can't actually set things on fire again even if I add more plasma (I can open a toxins canister directly over the igniter and it won't matter, toxins on the tile remains at 0). The canister, on the other hand, DOES still empty. Its contents however effectively vanish.

**Comment by HoaxIT** [comment]
@Aranclanos

**Comment by kyrahabattoir** [comment]
@WJohn That is weird and remind me a weird problem i had with the TEG yesterday, i had a burn chamber full of post combustion CO2, and vented it out for a while to prepare for a second load.

Once the second load was injected, impossible to light it on fire, it would die down almost immediately.

**Comment by optimumtact** [comment]
There might be a problem where the gas overlays don't go, but the gases themselves are gone.

Did you verify the contents of the air with a monitor?

**Comment by kyrahabattoir** [comment]
Yeah there is still plasma, i also did a standard draugh mode test and plasma did diffuse low enough to lose the purple specks, but was still high enough to be dangerous.

Honestly we need gasses to diffuse as long as tiles have composition differences, not just pressure differences.

**Comment by duncathan** [comment]
Was this fixed by #10593?

**Comment by kyrahabattoir** [comment]
It's better, but not quite fixed:
https://i.imgur.com/mNgruLH.png

**Comment by MrStonedOne** [comment]
Sadly this can't be easily fixed.

Spreading thresholds are done on the gas mixture as a whole. Fixing that would create a minor cpu increase in how atmos processes.

I did lower it by a factor of 10.

**Comment by Chnkr** [comment]
> Fixing that would create a minor cpu increase in how atmos processes

It's still a bug, bugs should be fixed imho.

**Comment by MrStonedOne** [comment]
There is also the side effect that toxins would be able to spread in an open run that didn't go into space until it no longer existed. This can already happen in certain cases.

I don't consider this a bug so much as an artifact of how gases work in real life. And we can't do what a real space station would do, and have scrubbers take in a little bit, and vents always pushing out a little bit, to cycle them, because of performance.

For the record for anybody reading this:
If you wanted to play around with this on a local server, you can just change [MINIMUM_AIR_RATIO_TO_SUSPEND](https://github.com/tgstation/-tg-station/blob/master/code/__DEFINES/atmospherics.dm#L30) to something lower. maybe 0.00001 (anything above 0)

**Comment by duncathan** [comment]
this won't get fixed without eating performance. as much as I want this to be fixed, the performance costs unfortunately are not worth it.
